version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=${{secrets.SECRET_KEY}}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${{secrets.DATABASE_PASSWORD}}
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
